name: Deno CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Start Server
        run: deno run --allow-net main.ts &
        
      - name: Wait for Server
        run: sleep 2

      - name: Run Tests
        run: deno test --allow-net
